name: Boost
main: Zedstar16\Boost\Main
version: 1.0
api: 3.7.0
load: POSTWORLD
author: Zedstar16
description: Fun plugin for just messing around lul
website: https://github.com/Zedstar16/Boost

commands:
 boost:
  description: "Boost yourself or other players"
  usage: ""
  permission: boost

permissions:
 boost:
  default: op
  description: "boost urself and mates"
  children:
   boost.self:
    default: op
    description: "boost urself"
